/* SKYSTRIKE — roster.js: jet roster DATA + ace-pool helpers.
   Pure & require-safe (no THREE / store / DOM) so Node tests require() the REAL roster
   instead of carrying a mirror copy. CommonJS footer (below) is inert in the browser.
   Load order: right after core.js, before globals.js (whose jetStats reads JETS at call-time). */

const JETS = [
  { id:'FT-1', shape:'STD', name:'FT-1 STANDARD', role:'Multirole Trainer', topSpeed:'Mach 1.4', ceiling:'48,000 ft', cannon:'20mm rotary', gen:'BASELINE',
    speed:6, agility:6, accel:6, armor:6, stealth:4, firepower:6, color:0x8a96a4, accent:0x5fb0d0,
    ability:null, abilityDesc:'', passive:null,
    desc:'A plain, dependable airframe — no tricks, no special. The baseline every pilot learns on.',
    context:'Generic trainer/multirole. A no-frills fourth-generation airframe with honest, middle-of-the-road handling and no signature weapon or party trick — the control against which the exotic jets in this hangar are measured.' },
  { id:'F-22', shape:'F22', name:'F-22 RAPTOR', role:'Air Superiority', topSpeed:'Mach 2.25', ceiling:'65,000 ft', cannon:'20mm M61A2', gen:'5th GEN',
    speed:8, agility:9, accel:9, armor:7, stealth:9, firepower:8, color:0x7fd8ff, accent:0x00ffe0,
    ability:'OVERDRIVE', abilityDesc:'Afterburner surge for 6s: +75% speed, +50% gun damage, and the cannon widens to a 4-round spread.',
    passive:'PRECISION GUNS \u2014 +20% cannon damage and a standing 10% chance to land a critical hit.',
    desc:'Thrust-vectoring all-rounder \u2014 no glaring weakness, deadly in any phase of the fight.',
    context:'Lockheed Martin \u00B7 USA. The world\u2019s first operational fifth-generation fighter, in USAF service since 2005. Its twin F119 engines with rectangular thrust-vectoring nozzles let it \u201Csupercruise\u201D \u2014 sustain supersonic flight without afterburner. Only 187 were built and U.S. law forbids exporting it; for two decades it has been the benchmark every other stealth fighter is measured against.' },
  { id:'F-35', shape:'F35', name:'F-35 LIGHTNING II', role:'Stealth Multirole', topSpeed:'Mach 1.6', ceiling:'50,000 ft', cannon:'25mm GAU-22/A', gen:'5th GEN',
    speed:6, agility:6, accel:6, armor:8, stealth:10, firepower:7, color:0x9ee86b, accent:0x39ff86,
    ability:'STEALTH FIELD', abilityDesc:'Active cloak for 7s; missiles fired while cloaked auto-home the nearest foe and ambush-kill any non-boss.',
    passive:'SENSOR FUSION \u2014 incoming missiles routinely lose lock and your own missiles hard-home. Modest cannon.',
    desc:'Software-defined stealth multirole; its real weapon is the picture it builds of the battle.',
    context:'Lockheed Martin \u00B7 USA. The most-produced stealth fighter in the world, built in three flavours: the A for runways, the jump-jet B for the Marines and amphibious ships, and the carrier C. Its real weapon is software \u2014 sensor fusion blends radar, infrared and electronic data into one picture and shares it across the formation. Flown by well over a dozen allied nations.' },
  { id:'J-20', shape:'J20', name:'J-20 MIGHTY DRAGON', role:'Interceptor', topSpeed:'Mach 2.0', ceiling:'66,000 ft', cannon:'None (PL-15)', gen:'5th GEN',
    speed:9, agility:6, accel:8, armor:6, stealth:8, firepower:9, color:0xc78bff, accent:0xff39c8,
    ability:'EMP PULSE', abilityDesc:'Wide-area EMP: scrambles enemy weapons 6s, detonates incoming missiles, and hands you a free instant lock on the nearest contact.',
    passive:'PL-15 SNIPER \u2014 NO cannon, but +50% missile damage, +10 missiles, lightning locks, and warheads burst on impact.',
    desc:'A pure long-range missile sniper that hunts high-value targets from stand-off range.',
    context:'Chengdu \u00B7 China. China\u2019s first fifth-generation fighter, operational since 2017. Big and long-ranged, its canard-delta layout and large internal bays are built around the long-reach PL-15 air-to-air missile \u2014 it is designed to hunt tankers, AWACS and other high-value targets from stand-off range rather than turn-and-burn in a knife fight. Early jets carry no internal gun.' },
  { id:'SU-57', shape:'SU57', name:'SU-57 FELON', role:'Multirole', topSpeed:'Mach 2.0', ceiling:'66,000 ft', cannon:'30mm GSh-30-1', gen:'5th GEN',
    speed:8, agility:10, accel:8, armor:7, stealth:6, firepower:9, color:0xff8b6a, accent:0xffc73a,
    ability:'COBRA', abilityDesc:'Post-stall snap: instant brake & flip, 1.5s invulnerability, plus a kinetic shockwave that guts nearby foes and shreds incoming missiles.',
    passive:'SUPERMANEUVER \u2014 +12% turn rate and grows deadlier as its health falls (up to +20% damage). Lighter hull.',
    desc:'Post-stall knife-fighter built to win the turning duel up close.',
    context:'Sukhoi \u00B7 Russia. Russia\u2019s first fifth-generation fighter, first flown in 2010 and fielded in small numbers from around 2020. It inherits the legendary supermaneuverability of the Flanker line \u2014 thrust-vectoring nozzles let it perform post-stall tricks like the Cobra \u2014 though its all-aspect stealth is widely judged less complete than its Western rivals.' },
  { id:'EFT', shape:'EFT', name:'EUROFIGHTER TYPHOON', role:'Air-Superiority', topSpeed:'Mach 2.0', ceiling:'65,000 ft', cannon:'27mm Mauser BK-27', gen:'4.5 GEN',
    speed:8, agility:9, accel:10, armor:6, stealth:3, firepower:7, color:0xffdf6a, accent:0xff8a2b,
    ability:'MISSILE SALVO', abilityDesc:'Salvo: 6 hard-homing missiles at +40% damage, spread across the nearest threats.',
    passive:'ENERGY FIGHTER \u2014 +15% cannon damage, +10% turn rate and fast locks, but a thin flare load and no stealth.',
    desc:'A computer-flown canard-delta prized for ferocious instantaneous turn and acceleration.',
    context:'Airbus / BAE / Leonardo \u00B7 Europe. A four-nation collaboration (UK, Germany, Italy, Spain) in service since 2003. Deliberately built unstable and flown by computer, its close-coupled canard-delta gives ferocious instantaneous turn and class-leading acceleration \u2014 a pure energy fighter prized for within-visual-range air superiority rather than stealth.' },
  { id:'RAFALE', shape:'RAFALE', name:'DASSAULT RAFALE', role:'Omnirole', topSpeed:'Mach 1.8', ceiling:'50,000 ft', cannon:'30mm GIAT 30', gen:'4.5 GEN',
    speed:8, agility:9, accel:9, armor:6, stealth:5, firepower:8, color:0x8694a6, accent:0x4f7bff,
    ability:'SPECTRA JAMMER', abilityDesc:'SPECTRA EW field: 6s of total missile immunity — incoming missiles go blind and enemies can\u2019t launch.',
    passive:'SPECTRA SUITE \u2014 +6 long-burning flares and a reflexive point-defense that sometimes swats incoming missiles.',
    desc:'Omnirole fighter with a world-class electronic-warfare suite that fights threats instead of hiding from them.',
    context:'Dassault \u00B7 France. France calls it \u201Comnirole\u201D \u2014 one airframe for air defence, strike, recon and carrier-borne nuclear deterrence. Its SPECTRA electronic-warfare suite is among the best in the world, jamming and spoofing threats instead of hiding from them. Combat-proven over Libya, Mali, Iraq and Syria, and exported to India, Egypt, Qatar, the UAE, Greece and Croatia.' },
  { id:'TEJAS', shape:'TEJAS', name:'HAL TEJAS', role:'Light Multirole', topSpeed:'Mach 1.8', ceiling:'52,000 ft', cannon:'23mm GSh-23', gen:'4.5 GEN',
    speed:7, agility:9, accel:8, armor:5, stealth:4, firepower:6, color:0xa9c2d6, accent:0xff8c2b,
    ability:'HOLO-DECOYS', abilityDesc:'Projects 3 holographic doubles that soak up enemy guns and missiles for 6s.',
    passive:'FEATHERWEIGHT \u2014 fastest shield regen in the hangar and +14% turn rate, on a fragile 70% hull.',
    desc:'A tiny tailless compound-delta \u2014 a darting, hard-to-pin target in a turning fight.',
    context:'HAL / ADA \u00B7 India. India\u2019s home-grown lightweight fighter, inducted by the Air Force in 2016 after a long development. One of the smallest and lightest combat jets flying, its tailless compound-delta wing makes it a tricky, darting target \u2014 the cornerstone of India\u2019s push for an indigenous aerospace industry.' },
  { id:'FA18', shape:'FA18', name:'F/A-18 SUPER HORNET', role:'Carrier Multirole', topSpeed:'Mach 1.8', ceiling:'50,000 ft', cannon:'20mm M61A2', gen:'4.5 GEN',
    speed:6, agility:8, accel:7, armor:8, stealth:4, firepower:8, color:0x8f9ba9, accent:0xffd24d,
    ability:'COMBAT TRANCE', abilityDesc:'Bullet-time: the world slows to 40% for 4s while you keep flying and firing at full speed.',
    passive:'ORDNANCE TRUCK \u2014 huge gun & missile magazines, a tough 115% hull, and 6 HP repaired on every kill.',
    desc:'A rugged carrier workhorse: forgiving, adaptable, and built to keep flying when hit.',
    context:'Boeing \u00B7 USA. The backbone of the U.S. Navy\u2019s carrier air wings \u2014 a larger, longer-ranged development of the original Hornet. Rugged, forgiving at the low speeds needed for carrier approaches, and endlessly adaptable; its EA-18G \u201CGrowler\u201D cousin is the West\u2019s primary carrier-based electronic-attack jet.' },
  { id:'F-47', shape:'F47', name:'F-47', role:'Air Dominance \u00B7 6th Gen', topSpeed:'Classified', ceiling:'Classified', cannon:'Classified', gen:'6th GEN',
    speed:9, agility:8, accel:8, armor:8, stealth:10, firepower:9, color:0x8f9aa8, accent:0xffcf3a,
    ability:'CCA SWARM', abilityDesc:'Deploys three vivid-blue Collaborative Combat Aircraft directly in front of you. They immediately hunt and gun down nearby threats for ~16s before standing down. The F-47\u2019s passive makes them hit 25% harder.',
    passive:'WING QUARTERBACK \u2014 balanced & stealthy, and every AI escort or CCA you field hits 25% harder.',
    desc:'The crewed centrepiece of a flight, built to direct teams of uncrewed combat aircraft.',
    context:'Boeing \u00B7 USA. Unveiled on 21 March 2025 as the crewed centrepiece of the U.S. Air Force\u2019s Next Generation Air Dominance (NGAD) program. The F-47 is designed less as a lone dogfighter and more as a \u201Cquarterback\u201D \u2014 a stealthy, long-range manned jet that directs teams of cheaper uncrewed Collaborative Combat Aircraft (CCAs) and is built around adaptive-cycle engines.' },
  { id:'J-36', shape:'J36', name:'J-36', role:'Heavy Stealth \u00B7 6th Gen', topSpeed:'Classified', ceiling:'Classified', cannon:'Internal AAM bays', gen:'6th GEN',
    speed:8, agility:5, accel:6, armor:9, stealth:9, firepower:10, color:0x59708f, accent:0x33e1ff,
    ability:'ORDNANCE STORM', abilityDesc:'Empties the bays: a saturation barrage of 10 hard-homing missiles at +55% damage spread across every nearby threat, and snaps a heavy ablative shield over the airframe.',
    passive:'SATURATION PLATFORM \u2014 enormous loadout & hull and missiles burst with a heavy blast. Sluggish in a turn.',
    desc:'A flying magazine meant to penetrate deep and unload a heavy salvo rather than dogfight.',
    context:'Chengdu \u00B7 China (demonstrator). A large tailless aircraft first seen flying on 26 December 2024. Its most striking features are a broad modified-delta planform with no vertical tails and an apparent three-engine (trijet) layout \u2014 hints at a long-range, high-payload platform meant to penetrate deep and carry a heavy load of missiles rather than dogfight. Almost everything about it is still secret.' },
  { id:'J-50', shape:'J50', name:'J-50', role:'Stealth Fighter \u00B7 6th Gen', topSpeed:'Classified', ceiling:'Classified', cannon:'Classified', gen:'6th GEN',
    speed:9, agility:9, accel:9, armor:6, stealth:8, firepower:8, color:0x6c7f96, accent:0x46ffd0,
    ability:'VECTOR SURGE', abilityDesc:'Swivels the wingtips and goes supermaneuverable for 6s: turn rate and thrust soar, every incoming missile loses its lock, and a searing plasma wake guts anything you cut close past.',
    passive:'PHANTOM AGILITY \u2014 +15% turn rate, very slippery to missiles, and a standing 10% critical-hit chance. Lighter hull.',
    desc:'A tailless phantom that steers on swivelling wingtips \u2014 nimble and slippery, lightly built.',
    context:'Shenyang / SAC \u00B7 China (demonstrator). A second Chinese sixth-generation design that surfaced in December 2024 \u2014 smaller and more fighter-like than the J-36. It is a tailless, twin-engine, lambda-wing jet that appears to use swivelling wingtips for control in place of vertical tails, and is rumoured to be aimed in part at future carrier operations.' },
];

/* ---- ace pool (pure over JETS) — moved out of THREE-coupled entities.js so tests/ace-pool.test.js imports the real impl ---- */
function aceShapePool() { return JETS.filter(j => j.shape !== 'STD').map(j => j.shape); }
function jetNameForShape(shape) { const j = JETS.find(x => x.shape === shape); return j ? j.name : shape; }

/* CommonJS export for Node tests — inert in the browser. */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { JETS, aceShapePool, jetNameForShape };
}
